# Canonical build, validation, and release-artifact entry points.

SHELL := /bin/sh
.SHELLFLAGS := -eu -c

DIST_DIR := dist
SOURCE_FILTER := doxygen-awk.awk
DIST_FILTER := $(DIST_DIR)/doxygen-awk.awk
DIST_CHECKSUM := $(DIST_FILTER).sha256
AWK_BIN ?= awk

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build checksums clean test test-source test-dist

all: build

## Build the exact consumer artifact with immutable provenance metadata.
##
## Build provenance remains comments so generated metadata cannot alter AWK
## record-processing behavior or introduce runtime namespace.
build: $(SOURCE_FILTER)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILTER)'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# DOXYGEN_AWK_VERSION=$(VERSION)'; \
		printf '%s\n' '# DOXYGEN_AWK_BUILD_DATE=$(BUILD_DATE)'; \
		printf '%s\n' '# DOXYGEN_AWK_BUILD_COMMIT=$(BUILD_COMMIT)'; \
		printf '%s\n' '#'; \
		tail -n +2 "$(SOURCE_FILTER)"; \
	} >"$(DIST_FILTER).tmp"
	chmod 0755 "$(DIST_FILTER).tmp"
	mv "$(DIST_FILTER).tmp" "$(DIST_FILTER)"

## Run the regression suite against maintained source and consumer output.
test: test-source test-dist

## Run the regression suite against the maintained source file.
test-source:
	DOXYGEN_AWK_FILTER="$(SOURCE_FILTER)" AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh

## Build and run the regression suite against the exact consumer artifact.
test-dist: build
	test "$$(head -n 1 "$(DIST_FILTER)")" = '#!/usr/bin/awk -f'
	grep -Fxq '# Generated by make build. Do not edit directly.' "$(DIST_FILTER)"
	grep -Fxq '# Source files: $(SOURCE_FILTER)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_AWK_VERSION=$(VERSION)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_AWK_BUILD_DATE=$(BUILD_DATE)' "$(DIST_FILTER)"
	grep -Fxq '# DOXYGEN_AWK_BUILD_COMMIT=$(BUILD_COMMIT)' "$(DIST_FILTER)"
	DOXYGEN_AWK_FILTER="$(DIST_FILTER)" AWK_BIN="$(AWK_BIN)" sh ./tests/run-tests.sh

## Generate the SHA-256 checksum for the exact consumer artifact.
checksums: build
	cd "$(DIST_DIR)" && sha256sum "$(notdir $(DIST_FILTER))" >"$(notdir $(DIST_CHECKSUM))"

clean:
	rm -rf "$(DIST_DIR)"

